// Holds the browser forward pass to the Python one.
//
// Run with:  node --test tests/web/
//
// This is the third implementation of a single function (PyTorch trains,
// numpy serves, this runs the static demo), so it needs the same kind of
// contract that tests/test_forward_parity.py gives the numpy port. The
// fixture is generated by scripts/export_web_model.py and carries the
// intermediate stages, so a failure says which stage diverged rather than
// only that the answer is wrong.

import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { extractWindowFeatures, FEATURE_NAMES } from '../../docs/assets/features.js';
import { BrowserModel, sigmoid } from '../../docs/assets/model.js';

const here = dirname(fileURLToPath(import.meta.url));
const assetsDir = join(here, '..', '..', 'docs', 'assets');

const golden = JSON.parse(readFileSync(join(here, 'golden.json'), 'utf8'));
const metadata = JSON.parse(readFileSync(join(assetsDir, 'model.json'), 'utf8'));
const binary = readFileSync(join(assetsDir, 'model.bin'));
// Copy into a clean ArrayBuffer: a Node Buffer may be a view into a larger
// pooled allocation, so its .buffer is not necessarily just this file.
const buffer = binary.buffer.slice(
  binary.byteOffset,
  binary.byteOffset + binary.byteLength,
);
const model = new BrowserModel(metadata, buffer);

/** Largest absolute difference between two sequences. */
function maxAbsDiff(a, b) {
  assert.equal(a.length, b.length, 'length mismatch');
  let worst = 0;
  let index = -1;
  for (let i = 0; i < a.length; i += 1) {
    const d = Math.abs(a[i] - b[i]);
    if (d > worst) {
      worst = d;
      index = i;
    }
  }
  return { worst, index };
}

test('the bundle matches the fixture it was generated with', () => {
  assert.equal(model.modelVersion, golden.modelVersion);
  assert.equal(model.windowSize, golden.windowSize);
  assert.equal(metadata.featureNames.join(','), FEATURE_NAMES.join(','));
});

test('every tensor in the manifest is present and correctly sized', () => {
  let floats = 0;
  for (const t of metadata.tensors) {
    const w = model.weights[t.name];
    assert.ok(w, `missing tensor ${t.name}`);
    assert.equal(w.length, t.length, `wrong length for ${t.name}`);
    floats += t.length;
  }
  assert.equal(floats, metadata.totalFloats);
});

test('per-window z-scoring matches Python', () => {
  for (const [i, c] of golden.cases.entries()) {
    const { sequence } = model.preprocess(Float64Array.from(c.window));
    const { worst, index } = maxAbsDiff(sequence, c.sequence);
    assert.ok(worst < 1e-4, `case ${i}: sequence differs by ${worst} at ${index}`);
  }
});

test('the ten statistical features match Python', () => {
  for (const [i, c] of golden.cases.entries()) {
    const raw = extractWindowFeatures(Float64Array.from(c.window));
    for (let f = 0; f < raw.length; f += 1) {
      // Relative tolerance: these are unnormalised and span several orders
      // of magnitude, from autocorrelation near 1 to range in the hundreds.
      const scale = Math.max(1, Math.abs(c.rawFeatures[f]));
      const diff = Math.abs(raw[f] - c.rawFeatures[f]) / scale;
      assert.ok(
        diff < 1e-4,
        `case ${i}: feature ${FEATURE_NAMES[f]} = ${raw[f]}, expected ${c.rawFeatures[f]}`,
      );
    }
  }
});

test('the scaled feature vector matches Python', () => {
  for (const [i, c] of golden.cases.entries()) {
    const { features } = model.preprocess(Float64Array.from(c.window));
    const { worst, index } = maxAbsDiff(features, c.scaledFeatures);
    assert.ok(
      worst < 1e-3,
      `case ${i}: scaled feature ${FEATURE_NAMES[index]} differs by ${worst}`,
    );
  }
});

test('deterministic logits match Python', () => {
  let worst = 0;
  for (const [i, c] of golden.cases.entries()) {
    const { sequence, features } = model.preprocess(Float64Array.from(c.window));
    const logit = model.logit(sequence, features, null);
    const diff = Math.abs(logit - c.logit);
    worst = Math.max(worst, diff);
    assert.ok(
      diff < 1e-3,
      `case ${i}: logit ${logit}, expected ${c.logit} (diff ${diff})`,
    );
  }
  assert.ok(worst < 1e-3, `worst logit difference ${worst}`);
});

test('deterministic probabilities match Python', () => {
  for (const [i, c] of golden.cases.entries()) {
    const p = model.predictProba(Float64Array.from(c.window));
    assert.ok(
      Math.abs(p - c.probability) < 1e-4,
      `case ${i}: probability ${p}, expected ${c.probability}`,
    );
  }
});

test('MC Dropout is stochastic and brackets the deterministic score', () => {
  const window = Float64Array.from(golden.cases[3].window);
  const result = model.score(window, 60, 1);
  assert.ok(result.std > 0, 'MC Dropout produced zero uncertainty');
  assert.ok(result.score >= 0 && result.score <= 1);
  assert.ok(result.lower >= 0 && result.upper <= 1);
  assert.ok(result.lower <= result.score && result.score <= result.upper);
  assert.equal(result.samples.length, 60);
});

test('MC Dropout is reproducible for a given seed', () => {
  const window = Float64Array.from(golden.cases[1].window);
  const a = model.score(window, 30, 7);
  const b = model.score(window, 30, 7);
  assert.equal(a.score, b.score);
  assert.equal(a.std, b.std);
  const c = model.score(window, 30, 8);
  assert.notEqual(a.score, c.score, 'a different seed should give a different draw');
});

test('more samples stabilise the mean', () => {
  const window = Float64Array.from(golden.cases[5].window);
  const spread = (n) => {
    const means = [];
    for (let seed = 0; seed < 15; seed += 1) means.push(model.score(window, n, seed).score);
    const mu = means.reduce((a, b) => a + b, 0) / means.length;
    return Math.sqrt(means.reduce((a, b) => a + (b - mu) ** 2, 0) / means.length);
  };
  assert.ok(spread(120) < spread(5));
});

test('Monte Carlo statistics match Python', () => {
  // The deterministic checks above cannot catch a missing dropout site: with
  // dropout off every site is the identity. Only the spread reveals it, which
  // is how the fused-fast-path bug in the torch backend was found. Tolerances
  // come from the sampling error: sigma from n draws has a relative standard
  // error near 1/sqrt(2n), so 40 repeats of n=30 leaves about 2% of noise on
  // the averaged sigma while a systematically missing site shows up as a much
  // larger gap. Kept low enough that the suite stays quick in CI.
  const repeats = 40;
  for (const [i, c] of golden.cases.entries()) {
    if (!c.mcReference) continue;
    const { nSamples, meanOfMeans, meanOfSigmas } = c.mcReference;
    const window = Float64Array.from(c.window);

    let meanTotal = 0;
    let sigmaTotal = 0;
    for (let seed = 0; seed < repeats; seed += 1) {
      const r = model.score(window, nSamples, seed + 1);
      meanTotal += r.score;
      sigmaTotal += r.std;
    }
    const mean = meanTotal / repeats;
    const sigma = sigmaTotal / repeats;

    assert.ok(
      Math.abs(mean - meanOfMeans) < 0.03,
      `case ${i}: MC mean ${mean.toFixed(4)}, Python ${meanOfMeans.toFixed(4)}`,
    );
    const ratio = sigma / meanOfSigmas;
    assert.ok(
      ratio > 0.85 && ratio < 1.15,
      `case ${i}: MC sigma ${sigma.toFixed(4)} vs Python ${meanOfSigmas.toFixed(4)} `
      + `(ratio ${ratio.toFixed(3)}). A systematic gap here usually means a `
      + 'dropout site is missing or misplaced.',
    );
  }
});

test('a wrong-length window is rejected rather than reshaped', () => {
  assert.throws(() => model.preprocess(Float64Array.from([1, 2, 3])), /expected/);
});

test('sigmoid is stable at the extremes', () => {
  assert.ok(Number.isFinite(sigmoid(-800)));
  assert.ok(Number.isFinite(sigmoid(800)));
  assert.equal(sigmoid(0), 0.5);
  assert.ok(sigmoid(-800) >= 0 && sigmoid(800) <= 1);
});
